- voctocore/lib/audiomix.py
- voctocore/lib/commands.py
- voctocore/lib/controlserver.py
- voctocore/lib/tcpmulticonnection.py
- voctocore/lib/tcpsingleconnection.py
- voctocore/lib/videomix.py
current commands:
* `message`
* `set_video_a`
* `get_video_a`
* `set_video_b`
* `get_video_b`
* `set_audio`
* `get_audio`
* `set_composite_mode`
* `get_composite_mode`
* `set_stream_status`
* `get_stream_status`
* `get_config`
`get_config` gives a base64-encoded ini-dump of the current config
> [WIP] add protocol features and minor fixes

- voctogui/lib/audioselector.py
- voctogui/lib/connection.py
At pyconza 2015 sprints we started investigating the viability of voctomix for future video recording usage, and in my testing I found a couple of small issues that had to be resolved to get the GUI running on my test VM. This PR fixes those that I found.
> Small fixes from pyconza2015

- voctocore/lib/controlserver.py
For what it's worth, here's how I killed #19.  Might be interesting in that it doesn't introduce a dependency on Twisted.
Sorry I didn't get around to submitting this until now.
> Kill idle busy-loops in voctocore

- example-scripts/control-server/generate-cut-list.py
> flush after print().

- example-scripts/gstreamer/source-remote-desktop-as-cam1.py
- example-scripts/gstreamer/source-remote-videotestsrc-as-cam1.py
- example-scripts/gstreamer/source-videotestsrc-as-cam1-with-networktime.py
- voctocore/README.md
- voctocore/lib/audiomix.py
- voctocore/lib/avpreviewoutput.py
- voctocore/lib/avrawoutput.py
- voctocore/lib/avsource.py
- voctocore/lib/clock.py
- voctocore/lib/streamblanker.py
- voctocore/lib/videomix.py
- voctocore/voctocore.py
- voctogui/lib/clock.py
- voctogui/lib/connection.py
- voctogui/lib/videodisplay.py
- voctogui/voctogui.py
it seems to work for me but there are subtile things like setting the base_time correct, which needs some testing. This kind of syncronization is required when core, gui or sources are running on different machines which drift differently.
It would probably fix #46 and fix #37
> Use GstNetworkTime to sync core, gui and sources

- example-scripts/gstreamer/source-nostream-music-from-folder.py
Add Tool to Play a complete Folder of Music against the Stream-Blank Audio-Input, fixes #14
> Audio Playback Tool

- voctocore/default-config.ini
- voctocore/lib/commands.py
- voctocore/lib/pipeline.py
- voctocore/lib/videomix.py
Allow Default-A/B Source for the composition modes
closes #77, closes #26 and closes #27
> Default composite

- README.md
Add a Link to @MaZderMind talk about Voctomix from Froscon 2016 to the ReadMe
> Add Voctomix Talk

- .gitignore
- example-scripts/.gitignore
to avoid this lintian warning:
https://lintian.debian.org/tags/package-contains-vcs-control-file.html
> merge example-scripts/.gitignore into .gitignore

- example-scripts/ffmpeg/stream-sd.sh
11000 would work as well, however it's unaffected by stream pause
> fixed port in ffmpeg/stream-sd.sh script

- example-scripts/ffmpeg/record-mixed-ffmpeg-segmented-timestamps.sh
- example-scripts/ffmpeg/record-mixed-ffmpeg-segmented.sh
- example-scripts/ffmpeg/record-mixed-ffmpeg.sh
and change FFmpeg examples to something that can be used with vanilla FFmpeg
> change subsampling to 420 because vocto currently uses 420 internally

- voctocore/default-config.ini
- voctocore/lib/audiomix.py
- voctocore/lib/pipeline.py
- voctocore/lib/streamblanker.py
- voctocore/lib/videomix.py
fixes #104
(bonus: example-configuration for pause-loop-image)
> adjustable pauseloop volume

- voctocore/lib/config.py
- voctocore/voctocore.py
- voctogui/lib/config.py
- voctogui/voctogui.py
> check for explicit config files

- .travis.yml
- check_pep8.sh
- voctocore/fake-gi.sh
- voctocore/lib/args.py
- voctocore/lib/config.py
- voctocore/test.sh
- voctocore/tests/helper/config_mock.py
- voctocore/tests/helper/voctomix_test.py
- voctocore/tests/test_config_getlist.py
- voctocore/voctocore.py
- voctogui/lib/args.py
- voctogui/lib/config.py
- voctogui/voctogui.py
Unit-Test Part of #139 including one unit-test and some fixes to the found problems in VocConfigParser.getlist
> unit tests

- example-scripts/ffmpeg/stream-facebook.sh
> add facebook streaming example

- example-scripts/voctomidi/lpd8-config.ini
Signed-off-by: Holger Levsen <holger@layer-acht.org>
> add link to lpd-8 productpage on akaipro.com

- example-scripts/ffmpeg/source-testvideo-with-3-audio-tracks-as-cam1.sh
- voctocore/default-config.ini
- voctocore/lib/audiomix.py
- voctocore/lib/avpreviewoutput.py
- voctocore/lib/avrawoutput.py
- voctocore/lib/pipeline.py
- voctocore/lib/sources/__init__.py
- voctocore/lib/sources/avsource.py
- voctocore/lib/sources/decklinkavsource.py
- voctocore/lib/sources/tcpavsource.py
- voctocore/lib/streamblanker.py
- voctocore/tests/helper/config_mock.py
fixes #154 
tests fehlen noch ;)
> WiP feature/154 multiaudio

- voctogui/ui/voctogui.css
- voctogui/ui/voctogui.ui
- voctogui/voctogui.py
> Add css styling and color indicators to source select buttons

- example-scripts/voctolight/voctolight.py
fixed a bug where the tallylight would activate when selecting its camera as source b even though another source was in fullscreen mode.
> Tallylight Bugfix

- voctocore/lib/commands.py
- voctocore/tests/commands/test_get_config_option.py
> add command to retrieve single config-options

- voctocore/lib/commands.py
- voctocore/tests/commands/test_get_composite_modes.py
> add command to retrieve list of composite modes

- voctogui/lib/studioclock.py
- voctogui/lib/ui.py
- voctogui/ui/voctogui.ui
minor speed improvements and better integration in UI file of `StudioClock`
> improve and review StudioClock

- example-scripts/ffmpeg/record-mixed-ffmpeg-segmented-timestamps.sh
- example-scripts/ffmpeg/record-mixed-ffmpeg.sh
Removed some options that actually don't do anything to make it work with FFmpeg 4.x
> Example scripts: fix compatibility issues with newer FFmpeg versions

- example-scripts/voctoremote/README.md
Added a little section to the readme to show how to listen on all interfaces or on a specific one
> Added a little section to the readme

- voctocore/lib/config.py
> voctocore/lib/config: rework code to use schedule.json instead of xml
