voc/voctomix

- voctocore/README.md
The command for getting the settings was falsely called 'get_setting' though it has to be 'get_config'
> Fix wrong command in README

- voctocore/default-config.ini
- voctocore/lib/avpreviewoutput.py
- voctogui/lib/videodisplay.py
This PR enables a new Config-Option `vaapi` in the `[previews]` which switches the preview-encoders to vaapi-accelerated hardware. This offloads the CPU quite a bit and quality vs. bandwidth is not an issue here either.
he UI has a rudimentary understanding of the different encoders and which decoders need to be used for them, although only `none` and `h264` have been tested yet.
> Experiment with vaapi for the Preview-Encoders

- .gitignore
- voctocore/default-config.ini
- voctocore/lib/audiomix.py
- voctocore/lib/pipeline.py
- voctocore/lib/videomix.py
- voctogui/lib/ui.py
- voctogui/lib/videodisplay.py
This pull request is addressing issue #63, the configuration option to pre-select the audio source.
If such a config option is given, the corresponding GUI element in voctogui is removed.
This is done to prevent accidentally changing the audio source during production.
this branch contains the following commits:
197e6d8 added configuration option to specify initial audio source
b52dd80 fixed undefined variable when no previews are used
7ac47d6 fixed log message when reading "side-by-side-preview" config
6459e64 ignore vim temp files
> Audiosource

- voctocore/lib/tcpmulticonnection.py
- voctocore/lib/tcpsingleconnection.py
On connection close voctocore doesn't close the sockets, leading
to a leak.
> fix for #117 (voctomix leaking file descriptors)

- voctocore/default-config.ini
- voctocore/lib/pipeline.py
This PR adds an option to disable mirror ports, by default the behavior is the same as before (although you need the "mirrors" section in the config file)
> Add option to disable mirror outputs

- example-scripts/gstreamer/source-background-loop.py
The current version only tries to open `config.sh`, resulting in an error message when started with the default config. My patch keeps looking for `config.sh` first, but if it doesn't exist, it tries `default-config.sh` as well.
> try using default config as well

- voctocore/default-config.ini
- voctocore/lib/audiomix.py
- voctocore/lib/config.py
- voctocore/lib/errors/configuration_error.py
- voctocore/lib/pipeline.py
- voctocore/tests/test_audiomix_multiple_sources.py
- voctogui/default-config.ini
- voctogui/lib/videopreviews.py
I tried to reverse-engeneer the format of the `audiosource` with multiple
sources and their volumes and found it to be "source:volume,source:volume"
With the merge of #110 we now have a way of specifying per-source properties.
This PR simplifies the configuration, so that
a) audiosource can only old one source which is a shorthand of setting the
specified source to volume=1.0
b) sources volume's are now specified as `[source.name] volume=1.00` and this is
the only way of specifying multiple audio-sources
I know this is a backward incompatible change, but moving towards a 1.0 I would
like to clean up the interface (which is mostly made out of the configuration)
to be as surprise-free as possible.
Also this new format would fit nicely with #104, where we could specify a …
> cleanup interface for setting multiple audio-source volumes

- voctocore/lib/commands.py
- voctocore/lib/videomix.py
- voctocore/tests/commands/test_set_videos_and_composite.py
- voctocore/tests/helper/voctomix_test.py
- voctocore/tests/videomix/test_videomixer_set_composite_mode.py
- voctocore/tests/videomix/test_videomixer_set_sources.py
This PR fixes #100 by not applying the default sources when a composite-mode is set together with a source in a `set_videos_and_composite` command. The defaults still apply when only the composite-mode is changed using a `set_videos_and_composite` or the sources and the composite-mode are changed individually.
Tests are added to ensure this behavior.
> do not apply default-source when composite-mode is set together with a video-source

- voctocore/default-config.ini
- voctocore/lib/videomix.py
- voctogui/ui/voctogui.ui
(Second attempt, first merge request can't be reopened…)
This branch adds a cropping element to the pipeline that allows the removal of a superfluous part of the image.
To do this, configuration items for the picture-in-picture and the side-by-side-preview mode were added. For the latter this allows the final mix to be set up for example like illustrated in the following schematic:
The reasoning behind this is, that source B usually shows the speaker who only occupies the middle part of the frame.
From a technical perspective, the cropping of each side of a source is determined by the corresponding newly introduced attribute of the PadState object (croptop, cropleft, cropbottom, cropright). These attributes are set just like xpos, ypos, width and height when choosing a new Mixer state.
If …
> Crop (second attempt)

- README.md
`touch` doesn't create directories, thus it has to be created before.
> README: add missing mkdir in 'Quickstart using Docker' section

- README.md
- docker-compose.yml
This PR adds a `docker-compose` file in order to simplify quickstart testing.
> Add a docker-compose file for quickstart testing

- voctogui/lib/audioleveldisplay.py
Improved CPU usage and look of the audio level display
After a first profiling session with voctogui I realized a CPU usage
peak at audioleveldisplay.py:22(on_draw). This drawing routine uses
move-to and line-to to create a gradient for displaying the audio levels
which I found quite expensive. I replaced it by code which draws four
rectangles for every channel by using cairo gradients which works much
faster.
Sorry for the temporary mess on the master branch where I accidentally committed eight changes which I have already reverted.
> improve audio level display

- voctogui/lib/studioclock.py
- voctogui/lib/warningoverlay.py
it seems to stop the lagging in the audio-level widget.
I also reduced the clock-redraw to twice a second, as I don't see a need for redrawing 10 times a second. Second-Accuracy is not really required here anyway.
fixes #218
> use GLib.timeout_add rather then GLib.timeout_add_seconds

- voctogui/default-config.ini
> change gui-default to x

- voctocore/default-config.ini
- voctocore/lib/sources/decklinkavsource.py
Video format type to use for decklinkavsources. Default value is set to auto which was automatically in use till now. Not setting this option in the voctocore config doesn't change current behaviour. With adding e.g. `video_format=8bit-argb` to a source section an explicit video format can be chosen if autodetection fails. All possible video formats can be listed via `gst-inspect-1.0 decklinkvideosrc`.
> Add config options for video-format

- voctogui/default-config.ini
- voctogui/lib/audioleveldisplay.py
- voctogui/lib/videodisplay.py
- voctogui/ui/voctogui.ui
This commit adds the possibility to show VU meters for all audiostreams. `vumeter=1` in `voctogui.ini` mimics the previous behaviour of showing only the first stereo pair. `vumeter=all` will show a VU meter for every configured audiostream and audiochannel without having to specify an explicit number. `vumeter=n` will show only show vumeters for all audio channels of first `n` audiostreams.
> VU meters for all audiostreams

- example-scripts/ffmpeg/stream-hd-to-youtube.sh
- example-scripts/ffmpeg/stream-hd.sh
- example-scripts/ffmpeg/stream-sd.sh
FFmpeg 4.1-1 as distributed in Debian Testing now won't start when using the current colon-based (`:`) syntax, so I replaced it with the new pipe-based (`|`) syntax, which solved the issue, and it has been already present within the FFmpeg examples, see `stream-combined.sh`
> replaced deprecated colon syntax for panning

- voctocore/lib/pipeline.py
Just a very small change, but should improve pipeline debuggability by outputting the actual debug message and not only a nondescriptive summary.
```
DEBUG Pipeline: ../gst/matroska/matroska-mux.c(1130): gst_matroska_mux_video_pad_setcaps (): /GstPipeline:pipeline0/GstBin:AVRawOutput-mix/GstMatroskaMux:mux-mix:
Caps changes are not supported by Matroska
Current: `video/x-raw, format=(string)I420, width=(int)1920, height=(int)1080, framerate=(fraction)25/1, pixel-aspect-ratio=(fraction)1/1, interlace-mode=(string)progressive, chroma-site=(string)jpeg, colori
metry=(string)bt601`
New: `video/x-raw, format=(string)I420, width=(int)1920, height=(int)1080, framerate=(fraction)25/1, pixel-aspect-ratio=(fraction)1/1, interlace-mode=(string)progressive, chroma-site=(string)mpeg2, colorimet …
```
> voctocore: output gstreamer debug message on pipeline error

- vocto/transitions.py
- voctocore/lib/videomix.py
fixes #305
Removing videobox and replacing it with a queue broke lecture mode. The element is necessary at that pont in the chain to enable correct cropping of sources in composite modes.
> voctocore: cropping in lecture mode

- voctocore/lib/sources/avsource.py
Hello from DebConf24! It seems our capture cards only do 1080i so we're stuck with deinterlacing for now :)
Sadly, the current code was crashing for us, as the yadif plugin has been deprecated in gstreamer 1.18. From the [1.18 release page](https://gstreamer.freedesktop.org/releases/1.18/):
> The yadif video deinterlacing plugin from gst-plugins-bad, which was one of the few GPL licensed plugins, has been removed in favour of deinterlace method=yadif.
We did try to use `deinterlace method=yadif` instead of the default, but it was choppy and much worse.
> gstreamer release 1.18 deprecated the yadif plugin.

- voctocore/lib/config.py
Commit 25f0da2ca9af0f2047a57a6ea9466c9a4a08ff38 removed the ability to load configuration from /etc/voctomix/voctocore.ini.
This patch adds a new configuration path hierarchy, which goes:
- configuration file from the CLI (-i foo.ini)
- $HOME/.config/voctomix/voctocore.ini
- /etc/voctomic/voctocore.ini
- default-config.ini
> Improve voctocore's default config paths

- voctocore/lib/sources/tcpavsource.py
Logging claims that the TCPAVSource listens on the mixer's hostname, but the hostname was never passed to GStreamer, which defaults to listening on localhost.
Thanks!
> TCPAVSource: listen on socket.gethostname() instead of localhost

- vocto/config.py
SafeConfigParser was removed in 3.12, after being deprecated since 3.2
Fixes: #330
> Python 3.12 support: use ConfigParser

- voctogui/lib/videodisplay.py
- voctogui/lib/videopreviews.py
v4l sources don't have audio, don't create a pipeline in the GUI to handle the audio in the preview. The lack of audio data just causes the preview to freeze on the first frame.
> Fix previews for v4l sources

- configs/2.0/minimal.ini
When doing R&D and testing automation and orchestration (whatever that means) it can be handy to have a config that is enough to get core up and running.  
put minimal.ini as  /etc/voctomix/voctocore.in 
```
$ voctocore -vv
...
INFO Pipeline: pipeline launched successfuly
INFO AudioMix: Updating mixer state
INFO VideoMix: Request composite full(CAM1,CAM2)
INFO Voctocore: Running. Waiting for connections....
INFO Scene: Pushing 1 frame(s) to source 'CAM1' at time 14ms
INFO Scene: Pushing 1 frame(s) to source 'CAM2' at time 14ms
```
> just enough ini so voctocore can run.

- pyproject.toml
Closes https://github.com/voc/voctomix/issues/339
Initial work to support PEP-517 packaging for python 3.9 - 3.11.
> add pyproject.toml & test installation against py3.9-11

- vocto/__init__.py
- voctocore/lib/avrawoutput.py
- voctogui/lib/audioonlydisplay.py
- voctogui/lib/videopreviews.py
- Alsa should be included in the audio only source list
- Don't try to mirror video for audio only sources
- VoctoGUI relies on VideoDisplay to update the audio levels, create an audio only alternative
> Fix audio only sources

- voctogui/lib/presetcontroller.py
Accelerator Groups need to be registered on the window to be able to react to key presses.
We already do this for all other toolbars, but not for presets.
> register preset hotkeys

- vocto/audio_streams.py
We used to order audio channels using `enumerate(set(t.split("+")))`. In Python, the iteration order for sets is random and changes with every run.
This commit uses a stable order (as specified in the config) instead
> Fix unstable audio channel order

- vocto/video_codecs.py
- voctogui/lib/videodisplay.py
Often enough we want to use vaapi encoding on the server, but a client may not support vaapi decoding. Ideally we'd decouple these entirely.
For now it's enough to couple client-side vaapi decoding and vaapi video rendering, as one doesn't make sense without the other (the additional GPU-RAM roundtrips destroy any potential performance benefits anyway).
> only use vaapi decode on the client if vaapi rendering is enabled

- vocto/__init__.py
- vocto/config.py
- voctocore/README.md
- voctocore/lib/sources/__init__.py
- voctocore/lib/sources/ajaavsource.py
This is mostly forked from the decklink source, but I switched it to using fstrings everywhere to make it (in my opinion) easier to read, and also added a use of the walrus (`:=`) operator.
Note: the config property `video_mode` actually maps to ajasrc's `video-format`; this is for closer alignment with the decklink source. There are a few other properties that could probably do with being exposed.
`device` currently defaults to the empty string, which will fail if used. We should maybe default it to `?`, which is a magic string that makes the AJA SDK output the list of attached devices (and their serial numbers, which are used as device identifiers), and then quit.
> add support for AJA capture cards

- voctogui/ui/voctogui.ui
Angels should mostly use presets. This PR puts them in the first tab which is autoselected on startup.
> Preset reorder
